apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    app: pgkafka-kafka-data
  name: pgkafka-kafka-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
